language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_2b79d61f6dc7_key -iv $encrypted_2b79d61f6dc7_iv -in samantha.jks.enc -out keys/samantha.jks -d
