language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_5eb4739780a3_key -iv $encrypted_5eb4739780a3_iv
  -in samantha.jks.enc -out keys/samantha.jks -d
